apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-{{ ansible_hostname }}-{{ item.0.key }}-{{ item.1 }}
spec:
  capacity:
    storage: '{{ item.0.value.size }}Gi'
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: '{{ item.0.value.path }}/{{ item.1 }}'
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ansible_hostname: !!null ''}: !!null ''}
