apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: rundeck
data:
  SECRET_PASSWORD: {{ vaulted.TESLA_PASSWORD|b64encode }}
  SECRET_USERNAME: {{ vaulted.TESLA_USERNAME|b64encode }}
type: Opaque


---

apiVersion: v1
kind: Secret
metadata:
  name: indigo-secrets
  namespace: rundeck
type: Opaque
data:
  INDIGO_USERNAME: {{ vaulted.INDIGO_USERNAME|b64encode }}
  INDIGO_PASSWORD: {{ vaulted.INDIGO_PASSWORD|b64encode }}
