apiVersion: v1
kind: Secret
metadata:
  name: indigo-secrets
  namespace: rundeck
type: Opaque
data:
  INDIGO_USERNAME: {{ vaulted.INDIGO_USERNAME|b64encode }}
  INDIGO_PASSWORD: {{ vaulted.INDIGO_PASSWORD|b64encode }}
