---

apiVersion: v1
kind: Secret
metadata:
  name: cava-passwords
type: Opaque
stringData:
  CAVA_USER: '{{ vaulted.CAVA_USER }}'
  CAVA_PASS: '{{ vaulted.CAVA_PASS }}'
  CAMERA_PASS: '{{ vaulted.LINUX_CLEAR_PASSWORD }}'
  INDIGO_USER: '{{ vaulted.INDIGO_USERNAME }}'
  INDIGO_PASS: '{{ vaulted.INDIGO_PASSWORD }}'
  TOMORROW_IO_API_KEY: '{{ vaulted.TOMORROW_IO }}'
