---

apiVersion: v1
kind: Secret
metadata:
  name: cava-passwords
type: Opaque
stringData:
  ICINGA_PASS: '{{ vaulted.data.icinga_api_users }}'
  CAVA_PASS: '{{ vaulted.data.CAVA_PASS }}'
  CAMERA_PASS: '{{ vaulted.data.LINUX_CLEAR_PASSWORD }}'
