---

apiVersion: v1
kind: Secret
metadata:
  name: cava-passwords
type: Opaque
stringData:
  ICINGA_PASS: '{{ vaulted.icinga_api_users }}'
  CAVA_PASS: '{{ vaulted.CAVA_PASS }}'
  CAMERA_PASS: '{{ vaulted.LINUX_CLEAR_PASSWORD }}'
  tomorrow_io_API_KEY: '{{ vaulted.TOMORROW_IO }}'
