apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: rundeck
data:
  SECRET_PASSWORD: {{ vaulted.TESLA_PASSWORD|b64encode }}
  SECRET_USERNAME: {{ vaulted.TESLA_USERNAME|b64encode }}
type: Opaque
