- name: Get a list of kubeconfig files
  command: ls {{ item }}
  register: dir_out
  delegate_to: localhost
  with_fileglob: /Users/david/.kube/*.kubeconfig
  become: false
  changed_when: false
  tags: kubeconfig

- name: Copy kubeconfigs to blanc
  copy:
    dest: /Users/admin/.kube
    src: '{{ item.item }}'
    group: staff
    owner: admin
    mode: '0644'
  delegate_to: blanc
  become: false
  changed_when: false
  tags: kubeconfig
  with_items: '{{ dir_out.results }}'
