---
# tasks file for arillso.sshd

- name: Install google authenticator PAM module
  become: true
  apt:
    name: 'libpam-google-authenticator'
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install google authenticator PAM module
  become: true
  yum:
    name: 'google-authenticator'
    state: present
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Oracle Linux'

- name: Add google auth module to PAM
  become: true
  pamd:
    name: 'sshd'
    type: 'auth'
    control: 'required'
    module_path: 'pam_google_authenticator.so'

- name: Remove password auth from PAM
  become: true
  pamd:
    name: 'sshd'
    type: 'auth'
    control: 'substack'
    module_path: 'password-auth'
    state: absent
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'Oracle Linux' or ansible_distribution == 'Amazon'

- name: Remove password auth from PAM
  become: true
  replace:
    dest: '/etc/pam.d/sshd'
    regexp: '^@include common-auth'
    replace: '#@include common-auth'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
