- name: Get a list of kubeconfig files
  command: ls {{ item }}
  register: dir_out
  delegate_to: localhost
  with_fileglob: /Users/david/.kube/*.kubeconfig
  become: false
  changed_when: false

- name: create /home/rundeck/.kube folder
  file:
      path: /home/rundeck/.kube
      group: rundeck
      state: directory
      owner: rundeck

- name: Copy kubeconfigs to host
  copy:
      dest: /home/rundeck/.kube
      src: "{{ item.item }}"
      group: rundeck
      owner: rundeck
  become: true
  changed_when: false
  tags: kubeconfig
  with_items: "{{dir_out.results }}"

- name: Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags: docker

- name: Add Docker APT repository for Raspbian
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian buster stable
    state: present

- name: Install docker engine (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: docker-ce
    state: present
    install_recommends: false
  tags: docker

- name: Install docker compose (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: docker-compose
    state: present
    install_recommends: false
  tags: docker

- name: Add Google Cloud Repo Key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes to Available apt Sources
  when:
    - ansible_os_family == "Debian"
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Install kubectl
  apt:
    name: kubectl
    state: present

- name: Add ssh private key to rundeck
  copy:
    dest: /home/rundeck/.ssh/id_rsa
    mode: "0600"
    owner: rundeck
    group: rundeck
    content: "{{ vaulted.data.id_rsa }}"

- name: Add ssh public key to rundeck
  copy:
    dest: /home/rundeck/.ssh/id_rsa.pub
    mode: "0600"
    owner: rundeck
    group: rundeck
    content: "{{ vaulted.data.id_rsa_pub }}"

- name: Add rundeck to docker group
  user:
    name: rundeck
    groups: docker
    append: yes
