apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: automatic
  namespace: metallb-system
spec:
  addresses:
  - 10.9.10.1-10.9.10.254
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static
  namespace: metallb-system
spec:
  addresses:
  - 10.9.9.200-10.9.9.254
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement1
  namespace: metallb-system
spec:
  ipAddressPools:
  - automatic
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement2
  namespace: metallb-system
spec:
  ipAddressPools:
  - static
---
