- name: Add static mounts for backups
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    opts: async,auto
    state: mounted
    fstype: nfs
    boot: yes
  loop:
  - {path: /System/Volumes/Data/backups/backups, src: 'shiraz:/mnt/RAIDZ/backups'}
  - {path: /System/Volumes/Data/backups/archive, src: 'shiraz:/mnt/RAIDZ/archive'}
  - {path: /System/Volumes/Data/backups/data, src: 'shiraz:/mnt/RAIDZ/data'}
  - {path: /System/Volumes/Data/backups/docker, src: 'shiraz:/mnt/RAIDZ/docker'}
