- name: Create Rundeck Secrets
  command: kubectl apply -f /usr/local/src/rundeck-secrets.yaml

# Create the pods and services
- name: Apply Cava Kustomize script
  shell: set -o pipefail && kustomize build prod | kubectl apply -f -
  args:
    executable: /bin/bash
    chdir: /usr/local/src/cava/k8s
  changed_when: false
  tags: cava
