- name: Add magicmirror user
  user:
    name: magicmirror
    create_home: yes
    groups:
      - video
      - audio
    uid: "1008"
    state: present
    password: "{{ vaulted.LINUX_PASSWORD }}" # pragma: allowlist secret
  notify: reboot server

- name: git config email
  git_config:
    name: user.email
    scope: global
    value: "david@davidsnider.org"
  become_user: magicmirror

- name: git config name
  git_config:
    name: user.name
    scope: global
    value: "David Snider"
  become_user: magicmirror

- name: disable overscan
  lineinfile:
    path: /boot/config.txt
    line: disable_overscan=1
    mode: "0755"
  notify: reboot server

- name: see if screenblanking is disabled
  command: raspi-config nonint get_blanking
  register: get_blanking
  changed_when: false

- name: Disable screen blanking
  command: raspi-config nonint do_blanking 1
  when:
    - "'1' not in get_blanking.stdout"
  notify: reboot server

- name: see if autologin is enabled
  command: raspi-config nonint get_autologin
  register: get_autologin
  changed_when: false

- name: Set autologin # noqa 305 command does not support variable setting
  shell: SUDO_USER=magicmirror raspi-config nonint do_boot_behaviour B4
  when:
    - "'0' not in get_autologin.stdout"
  notify: reboot server

- name: Ensure dependencies are present.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo.changed
  tags: ["skip_ansible_lint"]

- name: Ensure Node.js and MagicMirror dependencies are installed.
  apt:
    name:
      - devilspie2
      - jq
      - nodejs
      - wmctrl
    state: present

- name: Git reset before cloning # noqa 303
  command: git reset --hard
  args:
    chdir: /home/magicmirror/MagicMirror
  become_user: magicmirror
  changed_when: false
  failed_when: false

- name: Clone MagicMirror
  git:
    repo: https://github.com/MichMich/MagicMirror
    dest: /home/magicmirror/MagicMirror
    version: master
    accept_hostkey: yes
  become_user: magicmirror
  notify:
    - Install MagicMirror dependencies
    - restart magicmirror

- name: Install pm2
  npm:
    name: pm2
    global: yes
  notify: Start pm2 at boot

- name: Copy config.js
  template:
    src: config.js
    dest: /home/magicmirror/MagicMirror/config/config.js
    owner: magicmirror
    group: magicmirror
    mode: "0644"
  notify: restart magicmirror

- name: Copy mm.sh
  copy:
    src: mm.sh
    dest: /home/magicmirror/mm.sh
    owner: magicmirror
    group: magicmirror
    mode: "0755"
  register: mm_ssh
  notify:
    - restart magicmirror

- name: Check startup scripts
  shell: |
    set -o pipefail
    pm2 jlist|jq ".[0].pm2_env.pm_exec_path"
  args:
    executable: /bin/bash
  register: pm2_status
  become_user: magicmirror
  failed_when: false
  changed_when: false

- name: Setup startup scripts
  command: pm2 start mm.sh
  args:
    chdir: /home/magicmirror
  become_user: magicmirror
  when: "'/home/magicmirror/mm.sh' not in pm2_status.stdout"

- name: Save pm2 status
  command: pm2 save
  args:
    chdir: /home/magicmirror
  become_user: magicmirror
  when: "'/home/magicmirror/mm.sh' not in pm2_status.stdout"

- name: Check if wallpaper directory exists
  stat:
    path: /home/magicmirror/MagicMirror/modules/MMM-Wallpaper
  register: wallpaper_dir

- name: Reset Git
  command: git reset --hard
  args:
    chdir: /home/magicmirror/MagicMirror/modules/MMM-Wallpaper
  become_user: magicmirror
  changed_when: false
  when: wallpaper_dir.stat.exists

- name: Install wallpaper
  git:
    repo: https://github.com/kolbyjack/MMM-Wallpaper.git
    dest: /home/magicmirror/MagicMirror/modules/MMM-Wallpaper
    version: master
    accept_hostkey: yes
  become_user: magicmirror
  notify:
    - Install wallpaper dependencies
    - restart magicmirror

- name: Install monthly calendar
  git:
    repo: https://github.com/KirAsh4/calendar_monthly
    dest: /home/magicmirror/MagicMirror/modules/calendar_monthly
    version: master
    accept_hostkey: yes
  become_user: magicmirror
  notify:
    - Install monthly calendar dependencies
    - restart magicmirror

- name: Force HDMI mode on rpi
  blockinfile:
    path: /boot/config.txt
    block: |
      hdmi_group=1
      hdmi_mode=16
  notify: reboot server

- name: Install Countdown module
  git:
    repo: https://github.com/boazarad/MMM-CountDown.git
    dest: /home/magicmirror/MagicMirror/modules/MMM-CountDown
    version: master
    accept_hostkey: yes
  become_user: magicmirror
  notify:
    - Install countdown module dependencies
    - restart magicmirror

- name: Install IndoorTemperature-Endpoint
  git:
    repo: https://github.com/buxxi/MMM-IndoorTemperature-Endpoint.git
    dest: /home/magicmirror/MagicMirror/modules/MMM-IndoorTemperature-Endpoint
    version: master
    accept_hostkey: yes
  become_user: magicmirror
  notify:
    - Install indoor temperature module dependencies
    - restart magicmirror
