---

galaxy_info:
  author: sansible
  description: "Install SSMTP for Sending Mail."
  license: MIT
  min_ansible_version: 2.5
  min_ansible_container_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - development
# 
# dependencies:
#   - role: sansible.users_and_groups
#     sansible_users_and_groups_groups:
#       - name: "{{ sansible_ssmtp_group }}"
#     sansible_users_and_groups_users:
#       - name: "{{ sansible_ssmtp_user }}"
#         group: "{{ sansible_ssmtp_group }}"
#     when:
#       - sansible_ssmtp_group is not none
#       - sansible_ssmtp_user is not none
