apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: automatic
      protocol: layer2
      addresses:
      - {{ lb_range }}
    - name: static
      protocol: layer2
      addresses:
      - 10.9.9.200-10.9.9.254
      auto-assign: false
