- name: Install certbot
  apt:
    name: [certbot, python3-certbot-dns-route53]
    state: present

- name: Create AWS directory
  file:
    path: /root/.aws
    state: directory

- name: Add AWS Creds
  template:
    src: aws_credentials
    dest: /root/.aws/credentials
    owner: root
    group: root
    mode: '0600'

- name: Create certificate for vault.thesniderpad.com
  shell: . ~/.bashrc && certbot certonly --dns-route53 -d vault.thesniderpad.com -m david@davidsniderorg --agree-tos -n --eff-email
  args:
    creates: /etc/letsencrypt/live/vault.thesniderpad.com/cert.pem

- name: Create Vault directory
  file:
    path: /usr/local/vault
    state: directory

- name: Create Vault/config directory
  file:
    path: /usr/local/vault/config
    state: directory

- name: Create Vault/logs directory
  file:
    path: /usr/local/vault/logs
    state: directory

- name: Create Vault/policies directory
  file:
    path: /usr/local/vault/policies
    state: directory

- name: Copy docker-compose.yaml
  copy:
    dest: /usr/local/vault/docker-compose.yaml
    src: docker-compose.yaml

- name: Copy config.hcl
  template:
    dest: /usr/local/vault/config/config.hcl
    src: config.hcl

- name: Copy service file
  copy:
    dest: /etc/systemd/system/vault.service
    src: vault.service
  register: servicefile

- name: Register service file
  command: systemctl enable vault
  when: servicefile.changed

- name: Start vault service
  service:
    name: vault
    enabled: yes
    state: started

- name: Create monitoring for website
  template:
    dest: /shared/docker/icinga_master/conf.d/auto/vault.conf
    src: icinga_definition.conf
