---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: freenas-nfs-provisioner
  namespace: kube-system
  labels:
    app: freenas-nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freenas-nfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: freenas-nfs-provisioner
    spec:
      serviceAccountName: freenas-nfs-provisioner
      nodeSelector:
        beta.kubernetes.io/arch: arm
      containers:
        - name: freenas-nfs-provisioner
          image: docker.io/davidasnider/freenas-provisioner-arm:2.4
          env:
            #- name: IDENTIFIER
            #  value:
            #- name: PROVISIONER_NAME
            #  value:
