---
kind: Pod
apiVersion: v1
metadata:
  name: freenas-test-pod
spec:
  containers:
  - name: freenas-test-pod
    image: docker.io/ubuntu:latest
    command:
      - "/bin/bash"
    args:
      - "-c"
#      - "date >> /mnt/file.log && exit 0 || exit 1"
      - "dd if=/dev/zero of=/mnt/my_10mb_file bs=1M count=1000 && exit 0 || exit 1"
    volumeMounts:
      - name: freenas-test-volume
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: freenas-test-volume
      persistentVolumeClaim:
        claimName: freenas-test-pvc
