apiVersion: v1
kind: Namespace
metadata:
  name: channels

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels-dvr
  namespace: channels
spec:
  selector:
    matchLabels:
      app: channels-dvr
  template:
    metadata:
      labels:
        app: channels-dvr
    spec:
      hostNetwork: true
      hostname: channels-dvr
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: channels-dvr
        securityContext:
          privileged: true
        image: fancybits/channels-dvr:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        ports:
        - containerPort: 8089
        volumeMounts:
          - mountPath: /dev/dri
            name: dev-dri
          - mountPath: /channels-dvr
            name: config
          - mountPath: /shares/DVR
            name: dvr
      volumes:
      - name: dev-dri
        hostPath:
          path: /dev/dri
      - name: config
        nfs:
          server: 10.9.0.6
          path: /mnt/SEAGATE_4TB_SLOT5/channels-dvr/config
      - name: dvr
        persistentVolumeClaim:
          claimName: dvr-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvr-pvc
  namespace: channels
spec:
  storageClassName: fast-disks
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
