- import_playbook: turn_cluster_off.yaml

- import_playbook: reset_environment.yaml

- import_playbook: turn_cluster_on.yaml

- import_playbook: ../bootstrap/all_nodes_wait.yaml

- import_playbook: ../bootstrap/rpi_init.yaml
  when: hostvars[inventory_hostname].serial is defined

- import_playbook: ../bootstrap/intel_init.yaml
  when: hostvars[inventory_hostname].serial is not defined

- import_playbook: ../bootstrap/main.yaml
