- hosts: "{{ cluster }}"
  become: false
  gather_facts: no
  environment:
    VAULT_ADDR: https://vault.thesniderpad.com
  vars:
    vaulted: "{{ lookup('hashi_vault', 'url=https://vault.thesniderpad.com url=https://vault.thesniderpad.com secret=ansible/data/variables')}}" # pragma: allowlist secret
  tasks:

  - name: turn hosts off
    uri:
      url: "{{ power_url }}"
      method: PUT
      body: isOn=0
      status_code: 303
      url_username: '{{ vaulted.INDIGO_USERNAME }}'
      url_password: '{{ vaulted.INDIGO_PASSWORD }}' # pragma: allowlist secret
    when: power_url is defined
    delegate_to: localhost
