- hosts: "{{ cluster }}"
  become: false
  gather_facts: no
  vars:
    vaulted: "{{ lookup('hashi_vault', 'url=https://vault.thesniderpad.com secret=ansible/data/variables')}}" # pragma: allowlist secret
  tasks:

  - name: turn hosts on
    ansible.builtin.uri:
      url: "{{ indigo_base_url }}/command"
      method: POST
      body_format: json
      body:
        message: "indigo.device.turnOn"
        objectId: '{{ indigo_device_id }}'
      # status_code: 303
      headers:
        Authorization: "Bearer {{ vaulted.INDIGO_API_KEY }}"
    when: indigo_device_id is defined
    delegate_to: localhost
