---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: Install Brew Packages
    become: false
    homebrew:
      name: [
        'ansible',
        'black',
        'flake8',
        'htop',
        'iperf',
        'kubernetes-cli',
        'kustomize',
        'minikube',
        'nmap',
        'packer',
        'plantuml',
        'qemu',
        'watch',
        'wget',
        'wireshark',
        'zsh-autosuggestions',
        'zsh-history-substring-search',
        'zsh-syntax-highlighting',
      ]
      state: present
      update_homebrew: yes
      upgrade_all: yes

  - name: Install Brew Casks
    become: false
    homebrew_cask:
        name: [
          # '1password',
          'adoptopenjdk',
          'balenaetcher',
          'docker',
          'flowdock',
          'font-menlo-for-powerline',
          'font-meslo-for-powerline',
          'google-chrome',
          'google-cloud-sdk',
          'indigo',
          'istat-menus',
          'iterm2',
          'microsoft-office',
          'onedrive',
          'quicken',
          'virtualbox',
          'virtualbox-extension-pack',
          'wireshark',
          'x2goclient',
          'xquartz',
          ]
        state: present

  - name: install pip
    command: easy_install pip
    args:
      creates: /usr/local/bin/pip

  - name: install pip3
    command: easy_install-3.7 pip
    args:
      creates: /usr/local/bin/pip3

  - name: install sshpass
    become: false
    command: brew install http://git.io/sshpass.rb
    args:
      creates: /usr/local/bin/sshpass
      
  - name: Install python libraries globally
    pip:
      name:
        - requests

  - name: Install python libraries globally
    pip:
      name:
        - requests
      executable: pip3

# Todo Copy important files, .vscode directory, .zshrc, iterm profiles, istat menus
# todo install oh my zsh 
