- name: Register service file
  systemd:
    name: vault
    enabled: yes
    masked: no
    state: started

- name: Restart vault service
  service:
    name: vault
    enabled: yes
    state: restarted
