- name: install the latest version of collectd
  yum:
    name: collectd
    state: latest

- name: copy collectd config
  template:
    src: collectd.conf
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart collectd

- name: Start collectd service
  service:
    name: collectd
    state: started
    enabled: yes
