- import_tasks: debian.yaml
  when:
  - ansible_facts['os_family'] == "Debian"
  tags: debian

- import_tasks: raspbian.yaml
  when:
  - ansible_facts['os_family'] == "Debian"
  - ansible_architecture == "aarch64"

  tags: raspbian

- import_tasks: clearos.yaml
  when:
  - ansible_facts['os_family'] == "ClearOS"
  tags: clearos

- import_tasks: gen_rundeck_inventory.yaml
  tags: rundeck_inventory
  when: test_env is undefined
