- name: check node cluster status
  command: kubectl get node {{ ansible_hostname }}
  register: node_cluster_status
  delegate_to: '{{ masters[0] }}'
  changed_when: false
  ignore_errors: yes

- name: Install k3s service definition file
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
  when: node_cluster_status.failed

- name: Get the token for joining the cluster
  command: cat /var/lib/rancher/k3s/server/token
  register: join_token
  delegate_to: '{{ masters[0] }}'

- name: Create k3s config.yaml
  copy:
    dest: /etc/rancher/k3s/config.yaml
    content: |
      write-kubeconfig-mode: "0644"
      tls-san:
        - {{ vip }}
      disable:
        - servicelb
        - traefik
        - local-storage
      token: {{ join_token.stdout }}
      server: https://{{ masters[0] }}:6443
  when: node_cluster_status.failed

- name: start k3s service
  systemd:
    state: started
    enabled: true
    name: k3s
    daemon_reload: yes
    no_block: true
  when: node_cluster_status.failed

# Need the ' Ready' because NotReady is a valid status
- name: Wait for node to be ready
  command: kubectl get nodes {{ ansible_hostname }}
  register: nodes_status_ready
  retries: 30
  delay: 5
  until: '" Ready" in nodes_status_ready.stdout'
  when: node_cluster_status.failed
