- name: Add static mounts for videos
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    opts: async,auto
    state: mounted
    fstype: nfs
    boot: yes
  loop:
  - {path: /System/Volumes/Data/plex/videos, src: 'shiraz:/mnt/RAIDZ/videos'}
  - {path: /System/Volumes/Data/plex/home-videos, src: 'shiraz:/mnt/RAIDZ/home-videos'}
