- name: Add static mounts for videos
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    opts: async,auto
    state: mounted
    fstype: nfs
    boot: yes
  loop:
  - {path: /plex/mythtv_media, src: shiraz:/mnt/HITACHI_2TB_SLOT1/mythtv_media}
  - {path: /plex/mythtv_media1, src: shiraz:/mnt/SEAGATE_3TB_SLOT2/mythtv_media}
